[character]
success_symbol = "ğŸ¦„ ğŸ’¬ â¯"
error_symbol = "ğŸ¦„ ğŸ’¢ â¯"

[directory]
truncation_length = 0
truncate_to_repo = false

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
unknown_symbol = "ğŸ‘½ "

[[battery.display]]
threshold = 100

[git_branch]
symbol = "ğŸ„ "

[git_status]
conflicted = "âš”ï¸"
ahead = "ğŸ ğŸ’¨"
behind = "ğŸƒ ğŸ’¨"
untracked = "â—"
stashed = "ğŸ“¦"
modified = "ğŸ“"
added = "â•"
renamed = "ğŸ“›"
deleted = "ğŸ—‘"

