[character]
symbol = "ğŸ¦„ ğŸ’¬ â¯"
error_symbol = "ğŸ¦„ ğŸ’¢ â¯"
use_symbol_for_status = true

[directory]
truncation_length = 0
truncate_to_repo = false

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
unknown_symbol = "ğŸ‘½ "
threshold = 100.0
show_cycle = true

[git_branch]
symbol = "ğŸ„ "

[git_status]
conflicted = "âš”ï¸"
ahead = "ğŸ ğŸ’¨"
behind = "ğŸƒ ğŸ’¨"
untracked = "â—"
stashed = "ğŸ“¦"
modified = "ğŸ“"
added = "â•"
renamed = "ğŸ“›"
deleted = "ğŸ—‘"
